title: Onelight
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  zip_url: http://baidu.com
  another_url: another value

